[Variables]
Scanlines=#@#Images\scanlines.png      

;Here you can edit what each button does in each catagory
;ProgramXText is what will be displayed on the button, such as [Fallout 4]
;ProgramXTarget is where the button will lead to, such as a file path or a website URL

;Programs

Program1Text=Google Chrome
Program1Target=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Program2Text=Steam
Program2Target=S:\Steam\steam.exe
Program3Text=Skype
Program3Target=C:\Program Files (x86)\Skype\Phone\Skype.exe
Program4Text=Team Speak
Program4Target=C:\Program Files (x86)\TeamSpeak 3 Client\ts3client_win32.exe
Program5Text=Photoshop
Program5Target=C:\Program Files (x86)\Photoshop\Photoshop.exe

;Games
;By default, the games use steam to launch them, if you have a game that requires a file path, you can link to that aswell.

Game1Text=Counter Strike: GO
Game1Target=steam://rungameid/730
Game2Text=Rocket League
Game2Target=steam://rungameid/252950
Game3Text=The Binding of Isaac: Rebirth
Game3Target=steam://rungameid/250900
Game4Text=Prison Architect
Game4Target=steam://rungameid/233450
Game5Text=Fallout: New Vegas
Game5Target=steam://rungameid/22380

;Websites

Website1Text=Reddit
Website1Target=https://reddit.com
Website2Text=Youtube
Website2Target=https://youtube.com
Website3Text=Gmail
Website3Target=https://mail.google.com
Website4Text=Amazon
Website4Target=https://amazon.com
Website5Text=Netflix
Website5Target=https://netflix.com

;Sounds
;You can edit these but you will have to edit the [MeterSettings3] to have it reset to the correct sound file

Key1=#@#Sounds\key1.wav
Key2=#@#Sounds\key2.wav
Key3=#@#Sounds\key3.wav
Key4=#@#Sounds\key4.wav
Key5=#@#Sounds\key5.wav
PowerOn=#@#Sounds\poweron.wav
PowerOff=#@#Sounds\poweroff.wav
