;---------------------------------------------------------------------
; MEASURES

;---------------------------------------------------------------------
; METERS

[Background]
Meter=Image
MeterStyle=Style#Variant#Background

[Text]
Meter=STRING
MeterStyle=Style#Variant#Text
Text="Workspace 1"
LeftMouseUpAction=["\\mcls-dc03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Rainmeter\Skins\Enigma\@Resources\VD\Workspace1.exe.lnk"]

[Label]
Meter=STRING
MeterStyle=Style#Variant#Label
Text="2"