;--------------------------------------------------------------------------------------------
; ENIGMA DARK

[Variables]
Color1=255,255,255
Color2=#Color1#,160
Color3=#Color1#,108
Color4=#Color1#,25
ColorLink=128,192,255
ColorLink2=#ColorLink#,217
ColorLink3=#ColorLink#,160
ColorBorder=192, 192, 192
ColorBorder2=#ColorBorder#, 128
ColorBorder3=#ColorBorder#, 92
ColorBorder4=#ColorBorder#, 64
ColorPanel=24,24,24
ColorPanel2=#ColorPanel#,128
ColorFilter=0,0,0
ColorFilter2=#ColorFilter#,192
ColorFilter3=#ColorFilter#,128
ColorEvent=255,0,0
ColorEvent2=#ColorEvent#,92
ColorTransparent=0,0,0,2
ColorImage=W

Size1=11
Size4=8
Size3=9
Size2=10
Font=Trebuchet MS
SkinBackgroundAlpha=255
HideBordersTop=0
HideBordersBottom=0

SidebarWidth=370
SidebarSpacingFixed=1
SidebarAlpha=200
SidebarImage=#@#Images\Sidebar\SidebarLeft.#ColorImage#.jpg
SecondSidebarImage=#@#Images\Sidebar\SidebarRight.#ColorImage#.jpg

TaskbarHeight=44
TaskbarSpacingFixed=0
TaskbarAlpha=204
TaskbarImage=#@#Images\Taskbar\TaskbarTop.#ColorImage#.jpg
SecondTaskbarImage=#@#Images\Taskbar\TaskbarBottom.#ColorImage#.jpg
TaskbarMaxSkinWidth=200
TaskbarMinSkinWidth=60
TaskbarHideTriptych=1

SidebarClockFace=#@#Images\Clock\EnigmaClock.#ColorImage#.png
SidebarWorldClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
TaskbarClockFace=#@#Images\Clock\ChevronClock.#ColorImage#.png
