[Variables]

;-----------------------
; LAYOUT

Stylesheet=Enigma Dark

;-----------------------
; GENERAL

Note1Path=\\mcls-DC03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Rainmeter\Skins\Enigma\@Resources\User\Notes\Notes.txt
Note2Path=\\mcls-DC03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Rainmeter\Skins\Enigma\@Resources\User\Notes\Tasks.txt
Note3Path=\\mcls-DC03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Rainmeter\Skins\Enigma\@Resources\User\Notes\Scratchpad.txt
NoteHeight=200
Drive1=C
Drive2=S
Drive3=P
NetworkMaxDownload=1000000
NetworkMaxUpload=500000
SystemGraphType=Floating
CalendarEventFile=#@#User\Calendars\Holidays.xml
CalendarShowEvents=1
CalendarExtraDays=1
CalendarLeadingZeroes=0
CalendarMondays=0
GalleryPath=%USERPROFILE%\Pictures
GallerySubfolders=1
GalleryPosition=Center
GalleryRatio=3/4
VolumeIncrement=5
TriptychInterval=30
TriptychDisabled=1
ProcessInterval=5

;-----------------------
; MUSIC

MusicPlayerType=3
MusicPlayer=iTunes

;-----------------------
; FEEDS

Feed1=https://www.reddit.com/r/wallstreetbets.rss
Feed2=https://www.reddit.com/r/popular.rss
Feed3=https://www.reddit.com/r/programminghorror.rss
GmailUsername=YourUsernameHere
GmailPassword=YourPasswordHere
FacebookFeed=YourFacebookFeedHere
GoogleCalendar1=YourCalendarAddressHere
GoogleCalendar2=YourCalendarAddressHere
GoogleCalendar3=YourCalendarAddressHere
GoogleCalendarWriteEvents=1
RTMusername=YourUserNameHere
RTMpassword=YourPasswordHere
RTMlist1=YourListNumberHere
RTMlist2=YourListNumberHere
RTMlist3=YourListNumberHere
TwitterUsername=YourUsernameHere
TwitterPassword=YourPasswordHere

;-----------------------
; WORLD

WeatherCode=44418
WeatherCodeName=London
WeatherCodeLat=51.51
WeatherCodeLon=-0.13
Unit=c
World1WeatherCode=44418
World1WeatherCodeName=London
World1WeatherCodeLat=51.51
World1WeatherCodeLon=-0.13
World2WeatherCode=2514815
World2WeatherCodeName=Washington
World2WeatherCodeLat=38.9
World2WeatherCodeLon=-77.03
World3WeatherCode=455825
World3WeatherCodeName=Rio de Janeiro
World3WeatherCodeLat=-22.98
World3WeatherCodeLon=-43.2

;-----------------------
; APPS

App1=Chrome
App1Path=chrome.exe
App1PathHandle=chrome.exe
App1Label=Browser
App1Icon=#@#Images\Launcher\Chrome.#ColorImage#.png
App2=Notepad++
App2Path=C:\Program Files (x86)\Notepad++\notepad++.exe
App2PathHandle=notepad++.exe
App2Label=Text Editor
App2Icon=\\mcls-DC03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Rainmeter\Skins\Enigma\@Resources\Images\Launcher\NotepadPlusPlus.B.png
App3=Shout Outs
App3Path=\\mcls-ts01\c$\inetpub\wwwroot\shoutouts\ShoutOutsFiles
App3PathHandle=Rainmeter.exe
App3Label=Shortcut
App3Icon=\\mcls-DC03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Rainmeter\Skins\Enigma\@Resources\Images\Launcher\Chat.W.png
App4=Home
App4Path=\\mcls-DC03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Home Menu\hidebat.vbs
App4PathHandle=Rainmeter.exe
App4Label=Home Tabs
App4Icon=\\mcls-DC03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Rainmeter\Skins\Enigma\@Resources\Images\Launcher\Launcher.W.png
App5=Keepass
App5Path=C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe
App5Handle=rainmeter.exe
App5Label=Passwords
App5Icon=\\mcls-DC03\users\dylan\GitHub\Autohotkey\AIO Virtual Desktop\Rainmeter\Skins\Enigma\@Resources\Images\Launcher\Keepass.W.png

;-----------------------
; SEARCH

Search1=Google
Search1Command="http://google.com/search?q=$UserInput$"
Search1Icon=#@#Images\Search\Google.#ColorImage#.png
Search2=Wikipedia
Search2Command="http://en.wikipedia.org/wiki/$UserInput$"
Search2Icon=#@#Images\Search\Wiki.#ColorImage#.png
Search3=YouTube
Search3Command="http://www.youtube.com/results?search_query=$UserInput$"
Search3Icon=#@#Images\Search\YouTube.#ColorImage#.png
Search4=Twitter
Search4Command="https://twitter.com/#!/search/$UserInput$"
Search4Icon=#@#Images\Search\Twitter.#ColorImage#.png
Search5=Rainmeter.net
Search5Command="https://www.google.com/search?q=site%3Ahttp%3A%2F%2Frainmeter.net%2Fcms%2F%20$UserInput$"
Search5Icon=#@#Images\Search\Run.#ColorImage#.png
App5PathHandle=KeePass.exe
