; Change these variables to your desired setup

[Variables]
; The color of the sliding bars background
BgColor        = 58,90,111,50
; The color of the icons (Set this to 255,255,255 if your icons have color)
IconColor      = 255,255,255,255
; The amount of icons to show on each of the top & bottom slide bars
; "Do not forget to change this after you add more icons to the dock"
IconsToShowTop = 5
IconsToShowBot = 1

; Save your icons inside the "@Resources\Icons" folder
; IconName  >> The name of the icon file saved in the icons folder (Ex: steam.png)
; IconPath  >> The path of the app that you want to launch (Ex: C:\Program Files (x86)\Steam\Steam.exe)

;========= Mid Icons =========

MidIconName1 = github_2.png
MidIconPath1 = "C:\Users\dylan\AppData\Local\GitHubDesktop\GitHubDesktop.exe"
  
MidIconName2 = atom_2.png
MidIconPath2 = "C:\Users\dylan\AppData\Local\atom\atom.exe"
  
MidIconName3 = notepad++_2.png
MidIconPath3 = "C:\Program Files (x86)\Notepad++\notepad++.exe"

;========= Top Icons =========

TopIconName1 = visualstudio.png
TopIconPath1 = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe"
  
TopIconName2 = Microsoft_SQL_Server_Management_Studio_18_2.png
TopIconPath2 = "C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Ssms.exe"
  
TopIconName3 = MySQLWorkbench_2.png
TopIconPath3 = "C:\Program Files\MySQL\MySQL Workbench 8.0 CE\MySQLWorkbench.exe"
 
TopIconName4 = filezilla_2.png
TopIconPath4 = "C:\Program Files\FileZilla FTP Client\filezilla.exe"
 
TopIconName5 = wamp_2.png
TopIconPath5 = "C:\wamp64\wampmanager.exe"

;========= Bottom Icons =========

BottomIconName1 = config.png
BottomIconPath1 = "\\mcls-DC03\users\dylan\Rainmeter\Skins\Corner Dock\@Resources\Settings.inc"
  
BottomIconName2 = 
BottomIconPath2 = 
  
BottomIconName3 = 
BottomIconPath3 =
 
BottomIconName4 =
BottomIconPath4 =
 
BottomIconName5 =
BottomIconPath5 =

