[Variables]


URL=https://www.foreca.com/104528923/Zanesville-Muskingum-OH



UnitTypesTemp=
UnitTypesWind=
UnitTypesPress=ImperialUS
UnitTypesForecast=Imperial
SpeedUnit=mph
PressureUnit=inHg
UnitTypesSun=

DateFormat=%#d %h


SizeValue=0.70


FontFace=ITC Avant Garde Pro Bk
FontFace2=Segoe UI


FontColor=255,255,255
FontColor2=255,255,255,200
FontColor3=191,216,242,255
FontColor4=255,255,0


DayColor=0,0,0,120
OvercastColor=0,0,0,120
NightColor=0,0,0,120

RainColor=88,204,237

ShapeFill=0,0,0,120
ShapeStroke=120,120,120,255




























































































































































































